### ISSUE TITLE
Error when trying to open file with hdfs://ip:port/path

### ISSUE THREAD

**Issue by faladu** [PivotalRD/libhdfs3#16]
If I want to open a file with a path like hdfs://192.168.0.105:8020/tmp/test.txt i get an error.

The libhdfs3 seems to prolong the pathname to user/username/hdfs:://192.168.0.105:8020/tmp/test.txt which I guess it shouldn't do.

Full Error Message:

2015-06-18 00:43:00.575636, p39304, th140444680022112, ERROR Handle Exception: RpcHelper.h: 94: HdfsIOException: Unexpected exception: when unwrap the rpc remote exception "org.apache.hadoop.fs.InvalidPathException", Invalid path name /user/cloudera/hdfs:/192.168.0.16:8020/tmp/testfile00.txt
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2470)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2431)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:552)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.create(AuthorizationProviderProxyClientProtocol.java:108)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:388)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:587)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)
 in /home/dm/libhdfs3-apache-rpc-9/src/server/NamenodeImpl.cpp: 111
	@	Unknown
	@	Hdfs::Internal::UnWrapper<Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::NSQuotaExceededException, Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::FileNotFoundException, Hdfs::NSQuotaExceededException, Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::FileAlreadyExistsException, Hdfs::FileNotFoundException, Hdfs::NSQuotaExceededException, Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::DSQuotaExceededException, Hdfs::FileAlreadyExistsException, Hdfs::FileNotFoundException, Hdfs::NSQuotaExceededException, Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::UnWrapper<Hdfs::AlreadyBeingCreatedException, Hdfs::DSQuotaExceededException, Hdfs::FileAlreadyExistsException, Hdfs::FileNotFoundException, Hdfs::NSQuotaExceededException, Hdfs::ParentNotDirectoryException, Hdfs::UnresolvedLinkException, Hdfs::HdfsIOException, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing, Hdfs::Internal::Nothing>::unwrap(char const*, int)
	@	Hdfs::Internal::NamenodeImpl::create(std::string const&, Hdfs::Permission const&, std::string const&, int, bool, short, long)
	@	Hdfs::Internal::NamenodeProxy::create(std::string const&, Hdfs::Permission const&, std::string const&, int, bool, short, long)
	@	Hdfs::Internal::FileSystemImpl::create(std::string const&, Hdfs::Permission const&, int, bool, short, long)
	@	Hdfs::Internal::OutputStreamImpl::openInternal(std::shared_ptr<Hdfs::Internal::FileSystemInter>, char const*, int, Hdfs::Permission const&, bool, int, long)
	@	Hdfs::Internal::OutputStreamImpl::open(std::shared_ptr<Hdfs::Internal::FileSystemInter>, char const*, int, Hdfs::Permission const&, bool, int, long)
	@	Hdfs::OutputStream::open(Hdfs::FileSystem&, char const*, int, Hdfs::Permission, bool, int, long)
	@	hdfsOpenFile
	@	main
	@	Unknown
	@	Unknown

I searched for this behaviour and found something on snakebyte about it:

For operations: mv, test and tail - single_arg is used to carry hdfs
path, and there's no extra dirs for this operations thus CL parsing
method skipped single_args - in this commit make sure single_arg is
always included for this operations.

(Link: https://github.com/spotify/snakebite/issues/148)

Greetings Faladu

**Comment by wangzw** [comment]
Hi Faladu

To open a file, the "path" pass to hdfsOpenFile() cannot be a URL, it should be a path (absolute path such as "/path/to/a/file" or a relative path such as "a/relative/path").

**Comment by faladu** [comment]
Hm any reason why it differs there from the normal libhdfs?
It is strange that the normal libhdfs provides the URLs as path / filename when you use hdfsListDirectory and also accepts them as name for the hdfsopen but the libhdfs3 which uses the same headerfile doesn't.

Any reason why the implementation differs at that point?

**Comment by wangzw** [comment]
Hi Faladu

Good question.

We try to keep the same behaviors with libhdfs, but please consider this case.

User first create a filesystem and connect to cluster "hdfs://clusterA:9000" and then try to open a file on another cluster "hdfs://clusterB:9000/path/to/file", what will happen?

hdfsFS FS = hdfsConnect("clusterA", 9000);
hdfsFile file = hdfsOpenFile(FS, "hdfs://clusterB:9000/path/to/file", ...);  // what will happen?

Since FS is connected to clusterA but the "path" point to clusterB, this does not make sense. That is why we do not want to keep cluster info in "path", it will duplicate cluster info and make confusion.

It is true that we can improve libhdfs3's implementation to support pass a URI in hdfsOpenFile() and check if the cluster in URI is the same with the file system object passed by the user. Report error if they are not the same. You can consider it as an unimplemented feature and patch is welcomed.

**Comment by kdunn-pivotal** [comment]
Apologies for the *very* delayed response. The development team managing this codebase is also responsible for [Apache HAWQ](http://hawq.incubator.apache.org/) (incubating) and trying to get the first release out the door. As a result, this repo has been unintentionally neglected and recently turned read-only. 

This code was birthed from HAWQ and will be [merged](https://issues.apache.org/jira/browse/HAWQ-1046) back into into that project (now that it is open source as well); [mailing lists](http://mail-archives.apache.org/mod_mbox/incubator-hawq-dev/), pull requests, [issues](https://issues.apache.org/jira/browse/HAWQ) and releases related to libhdfs3 will be there. The plan is to provide [tarball releases](https://issues.apache.org/jira/browse/HAWQ-1058) of this code separate from the larger HAWQ project until it can be relocated into a dedicated repo again (down the road) - see [HAWQ-1059](https://issues.apache.org/jira/browse/HAWQ-1059).

Again, thank you for the contribution and patience while we sort out these logistics. 

@faladu if this issue/feature is still useful, please respond.
